# Generated by Django 5.2.7 on 2025-10-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caller_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField(auto_now_add=True)),
                ('duration', models.IntegerField(help_text='Duration in seconds')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
