# Generated by Django 5.2.7 on 2025-10-28 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calllog',
            old_name='call_time',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='notes',
        ),
        migrations.AddField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('missed', 'Missed'), ('completed', 'Completed'), ('ongoing', 'Ongoing')], default='ongoing', max_length=10),
        ),
        migrations.AddField(
            model_name='calllog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='caller_name',
            field=models.CharField(max_length=255),
        ),
    ]
